/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | {
            reference?: never;
            _type: "internalLink";
            _key: string;
          }
        | {
            href?: string;
            _type: "link";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & Code)
>;

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: BlockContent;
  publishDate?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type BlogCategory = {
  _id: string;
  _type: "blogCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  priority?: number;
};

export type BlogCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogCategory";
};

export type PublicProfileReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "publicProfile";
};

export type BlogPostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogPost";
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  featured?: boolean;
  categories?: Array<
    {
      _key: string;
    } & BlogCategoryReference
  >;
  author?: PublicProfileReference;
  body?: BlockContent;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  relatedPosts?: Array<
    {
      _key: string;
    } & BlogPostReference
  >;
  publishDate?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type PublicProfile = {
  _id: string;
  _type: "publicProfile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  image?: string;
  link?: string;
};

export type ItemReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "item";
};

export type Collection = {
  _id: string;
  _type: "collection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<
    {
      _key: string;
    } & ItemReference
  >;
  name?: string;
  slug?: Slug;
  description?: string;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    items?: Array<
      {
        _key: string;
      } & ItemReference
    >;
    alt?: string;
    _type: "image";
  };
  priority?: number;
};

export type GroupReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "group";
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  group?: GroupReference;
  priority?: number;
};

export type Group = {
  _id: string;
  _type: "group";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  priority?: number;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type Item = {
  _id: string;
  _type: "item";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  link?: string;
  affiliateLink?: string;
  introduction?: Markdown;
  visible?: boolean;
  version?: number;
  publishDate?: string;
  featured?: boolean;
  sponsor?: boolean;
  sponsorStartDate?: string;
  sponsorEndDate?: string;
  submitter?: {
    name?: string;
    image?: string;
    link?: string;
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type Markdown = string;

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type MediaFolderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "media.folder";
};

export type MediaFolder = {
  _id: string;
  _type: "media.folder";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: MediaFolderReference;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | Settings
  | Page
  | Slug
  | BlogCategory
  | BlogCategoryReference
  | PublicProfileReference
  | BlogPostReference
  | BlogPost
  | SanityImageCrop
  | SanityImageHotspot
  | PublicProfile
  | ItemReference
  | Collection
  | GroupReference
  | Category
  | Group
  | Tag
  | CategoryReference
  | TagReference
  | Item
  | Markdown
  | Code
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: itemByIdQuery
// Query: *[_type == "item" && visible == true && _id == $id][0] {    _id,  _createdAt,  name,  slug,  description,  link,  affiliateLink,  sponsor,  sponsorStartDate,  sponsorEndDate,  featured,  icon {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  image {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  publishDate,  submitter{name,image,link},  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},  categories[]->,  tags[]->,}
export type ItemByIdQueryResult = {
  _id: string;
  _createdAt: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  link: string | null;
  affiliateLink: string | null;
  sponsor: boolean | null;
  sponsorStartDate: string | null;
  sponsorEndDate: string | null;
  featured: boolean | null;
  icon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  publishDate: string | null;
  submitter: {
    name: string | null;
    image: string | null;
    link: string | null;
  } | null;
  collections: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }>;
  categories: Array<{
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    group?: GroupReference;
    priority?: number;
  }> | null;
  tags: Array<{
    _id: string;
    _type: "tag";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: itemInfoBySlugQuery
// Query: *[_type == "item" && visible == true && slug.current == $slug][0] {    _id,  _createdAt,  name,  slug,  description,  link,  affiliateLink,  sponsor,  sponsorStartDate,  sponsorEndDate,  featured,  icon {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  image {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  publishDate,  submitter{name,image,link},  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},  categories[]->,  tags[]->,}
export type ItemInfoBySlugQueryResult = {
  _id: string;
  _createdAt: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  link: string | null;
  affiliateLink: string | null;
  sponsor: boolean | null;
  sponsorStartDate: string | null;
  sponsorEndDate: string | null;
  featured: boolean | null;
  icon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  publishDate: string | null;
  submitter: {
    name: string | null;
    image: string | null;
    link: string | null;
  } | null;
  collections: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }>;
  categories: Array<{
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    group?: GroupReference;
    priority?: number;
  }> | null;
  tags: Array<{
    _id: string;
    _type: "tag";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: itemFullInfoByIdQuery
// Query: *[_type == "item" && visible == true && _id == $id][0] {      _id,  _createdAt,  name,  slug,  description,  link,  affiliateLink,  sponsor,  sponsorStartDate,  sponsorEndDate,  featured,  icon {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  image {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  publishDate,  submitter{name,image,link},  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},  categories[]->,  tags[]->,  introduction,}
export type ItemFullInfoByIdQueryResult = {
  _id: string;
  _createdAt: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  link: string | null;
  affiliateLink: string | null;
  sponsor: boolean | null;
  sponsorStartDate: string | null;
  sponsorEndDate: string | null;
  featured: boolean | null;
  icon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  publishDate: string | null;
  submitter: {
    name: string | null;
    image: string | null;
    link: string | null;
  } | null;
  collections: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }>;
  categories: Array<{
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    group?: GroupReference;
    priority?: number;
  }> | null;
  tags: Array<{
    _id: string;
    _type: "tag";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
  }> | null;
  introduction: Markdown | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: itemFullInfoBySlugQuery
// Query: *[_type == "item" && visible == true && slug.current == $slug&& visible == true] [0] {    introduction,  "related": *[_type == "item" && visible == true && defined(slug.current)    && defined(publishDate)    && visible == true    && !(sponsor == true && sponsorStartDate <= now() && sponsorEndDate > now())    && count(categories[@._ref in ^.categories[]._ref]) > 0 && _id != ^._id]    | order(publishDate desc, _createdAt desc) [0...3] {        _id,  _createdAt,  name,  slug,  description,  link,  affiliateLink,  sponsor,  sponsorStartDate,  sponsorEndDate,  featured,  icon {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  image {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  publishDate,  submitter{name,image,link},  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},  categories[]->,  tags[]->,  },    _id,  _createdAt,  name,  slug,  description,  link,  affiliateLink,  sponsor,  sponsorStartDate,  sponsorEndDate,  featured,  icon {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  image {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  publishDate,  submitter{name,image,link},  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},  categories[]->,  tags[]->,}
export type ItemFullInfoBySlugQueryResult = {
  introduction: Markdown | null;
  related: Array<{
    _id: string;
    _createdAt: string;
    name: string | null;
    slug: Slug | null;
    description: string | null;
    link: string | null;
    affiliateLink: string | null;
    sponsor: boolean | null;
    sponsorStartDate: string | null;
    sponsorEndDate: string | null;
    featured: boolean | null;
    icon: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      blurDataURL: string | null;
      imageColor: string | null;
    } | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      blurDataURL: string | null;
      imageColor: string | null;
    } | null;
    publishDate: string | null;
    submitter: {
      name: string | null;
      image: string | null;
      link: string | null;
    } | null;
    collections: Array<{
      _id: string;
      name: string | null;
      slug: Slug | null;
    }>;
    categories: Array<{
      _id: string;
      _type: "category";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      description?: string;
      group?: GroupReference;
      priority?: number;
    }> | null;
    tags: Array<{
      _id: string;
      _type: "tag";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      description?: string;
    }> | null;
  }>;
  _id: string;
  _createdAt: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  link: string | null;
  affiliateLink: string | null;
  sponsor: boolean | null;
  sponsorStartDate: string | null;
  sponsorEndDate: string | null;
  featured: boolean | null;
  icon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  publishDate: string | null;
  submitter: {
    name: string | null;
    image: string | null;
    link: string | null;
  } | null;
  collections: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }>;
  categories: Array<{
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    group?: GroupReference;
    priority?: number;
  }> | null;
  tags: Array<{
    _id: string;
    _type: "tag";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: itemListQuery
// Query: *[_type == "item" && visible == true && defined(slug.current)  && defined(publishDate)  && visible == true  && !(sponsor == true && sponsorStartDate <= now() && sponsorEndDate > now())]  | order(coalesce(featured, false) desc, publishDate desc) {      _id,  _createdAt,  name,  slug,  description,  link,  affiliateLink,  sponsor,  sponsorStartDate,  sponsorEndDate,  featured,  icon {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  image {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  publishDate,  submitter{name,image,link},  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},  categories[]->,  tags[]->,}
export type ItemListQueryResult = Array<{
  _id: string;
  _createdAt: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  link: string | null;
  affiliateLink: string | null;
  sponsor: boolean | null;
  sponsorStartDate: string | null;
  sponsorEndDate: string | null;
  featured: boolean | null;
  icon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  publishDate: string | null;
  submitter: {
    name: string | null;
    image: string | null;
    link: string | null;
  } | null;
  collections: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }>;
  categories: Array<{
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    group?: GroupReference;
    priority?: number;
  }> | null;
  tags: Array<{
    _id: string;
    _type: "tag";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: sponsorItemListQuery
// Query: *[_type == "item" && visible == true && defined(slug.current)  && defined(publishDate)  && visible == true  && sponsor == true  && sponsorStartDate <= now()  && sponsorEndDate >= now()]  | order(coalesce(featured, false) desc, publishDate desc) {      _id,  _createdAt,  name,  slug,  description,  link,  affiliateLink,  sponsor,  sponsorStartDate,  sponsorEndDate,  featured,  icon {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  image {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  publishDate,  submitter{name,image,link},  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},  categories[]->,  tags[]->,}
export type SponsorItemListQueryResult = Array<{
  _id: string;
  _createdAt: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  link: string | null;
  affiliateLink: string | null;
  sponsor: boolean | null;
  sponsorStartDate: string | null;
  sponsorEndDate: string | null;
  featured: boolean | null;
  icon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  publishDate: string | null;
  submitter: {
    name: string | null;
    image: string | null;
    link: string | null;
  } | null;
  collections: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }>;
  categories: Array<{
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    group?: GroupReference;
    priority?: number;
  }> | null;
  tags: Array<{
    _id: string;
    _type: "tag";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: itemListOfFeaturedQuery
// Query: *[_type == "item" && visible == true && defined(slug.current)  && defined(publishDate)  && visible == true  && !(sponsor == true && sponsorStartDate <= now() && sponsorEndDate > now())  && featured == true]  | order(coalesce(featured, false) desc, publishDate desc) [0...$count] {      _id,  _createdAt,  name,  slug,  description,  link,  affiliateLink,  sponsor,  sponsorStartDate,  sponsorEndDate,  featured,  icon {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  image {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  publishDate,  submitter{name,image,link},  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},  categories[]->,  tags[]->,}
export type ItemListOfFeaturedQueryResult = Array<{
  _id: string;
  _createdAt: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  link: string | null;
  affiliateLink: string | null;
  sponsor: boolean | null;
  sponsorStartDate: string | null;
  sponsorEndDate: string | null;
  featured: boolean | null;
  icon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  publishDate: string | null;
  submitter: {
    name: string | null;
    image: string | null;
    link: string | null;
  } | null;
  collections: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }>;
  categories: Array<{
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    group?: GroupReference;
    priority?: number;
  }> | null;
  tags: Array<{
    _id: string;
    _type: "tag";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: itemListOfLatestQuery
// Query: *[_type == "item" && visible == true && defined(slug.current)  && defined(publishDate)  && visible == true  && !(sponsor == true && sponsorStartDate <= now() && sponsorEndDate > now())]  | order(coalesce(featured, false) desc, publishDate desc) [0...$count] {      _id,  _createdAt,  name,  slug,  description,  link,  affiliateLink,  sponsor,  sponsorStartDate,  sponsorEndDate,  featured,  icon {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  image {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  publishDate,  submitter{name,image,link},  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},  categories[]->,  tags[]->,}
export type ItemListOfLatestQueryResult = Array<{
  _id: string;
  _createdAt: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  link: string | null;
  affiliateLink: string | null;
  sponsor: boolean | null;
  sponsorStartDate: string | null;
  sponsorEndDate: string | null;
  featured: boolean | null;
  icon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  publishDate: string | null;
  submitter: {
    name: string | null;
    image: string | null;
    link: string | null;
  } | null;
  collections: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }>;
  categories: Array<{
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    group?: GroupReference;
    priority?: number;
  }> | null;
  tags: Array<{
    _id: string;
    _type: "tag";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: collectionListQuery
// Query: *[_type == "collection" && defined(slug.current)]  | order(priority desc) {      ...,  icon {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },}
export type CollectionListQueryResult = Array<{
  _id: string;
  _type: "collection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<
    {
      _key: string;
    } & ItemReference
  >;
  name?: string;
  slug?: Slug;
  description?: string;
  icon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    items?: Array<
      {
        _key: string;
      } & ItemReference
    >;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  priority?: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: collectionQuery
// Query: *[_type == "collection" && slug.current == $slug][0] {    ...,  icon {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },}
export type CollectionQueryResult = {
  _id: string;
  _type: "collection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<
    {
      _key: string;
    } & ItemReference
  >;
  name?: string;
  slug?: Slug;
  description?: string;
  icon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    items?: Array<
      {
        _key: string;
      } & ItemReference
    >;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  priority?: number;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: groupListQuery
// Query: *[_type=="group"] | order(priority desc, _createdAt asc) {    ...,  "categories": *[_type=='category' && references(^._id)] | order(priority desc, _createdAt asc)  {    ...,  }}
export type GroupListQueryResult = Array<{
  _id: string;
  _type: "group";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  priority?: number;
  categories: Array<{
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    group?: GroupReference;
    priority?: number;
  }>;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: categoryListQuery
// Query: *[_type == "category" && defined(slug.current)]  | order(priority desc) {      ...,}
export type CategoryListQueryResult = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  group?: GroupReference;
  priority?: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: categoryQuery
// Query: *[_type == "category" && slug.current == $slug][0] {    ...,}
export type CategoryQueryResult = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  group?: GroupReference;
  priority?: number;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: tagListQuery
// Query: *[_type == "tag" && defined(slug.current)]  | order(slug.current asc) {      ...,}
export type TagListQueryResult = Array<{
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: tagQuery
// Query: *[_type == "tag" && slug.current == $slug][0] {    ...,}
export type TagQueryResult = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: pageQuery
// Query: *[_type == "page" && slug.current == $slug][0] {    ...,    body[]{      ...,      markDefs[]{        ...,        _type == "internalLink" => {          "slug": @.reference->slug        }      }    },  }
export type PageQueryResult = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference?: never;
              _type: "internalLink";
              _key: string;
              slug: null;
            }
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
        markDefs: null;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  > | null;
  publishDate?: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: blogCategoryListQuery
// Query: *[_type == "blogCategory" && defined(slug.current)]  | order(priority desc) {      name,  slug,  description,  priority,}
export type BlogCategoryListQueryResult = Array<{
  name: string | null;
  slug: Slug | null;
  description: string | null;
  priority: number | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: blogCategoryMetadateQuery
// Query: *[_type == "blogCategory" && slug.current == $slug][0] {      name,  slug,  description,  priority,  }
export type BlogCategoryMetadateQueryResult = {
  name: string | null;
  slug: Slug | null;
  description: string | null;
  priority: number | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: blogPostQuery
// Query: *[_type == "blogPost" && slug.current == $slug][0] {      relatedPosts[]-> {      _id,  _createdAt,  title,  slug,  excerpt,  featured,  image {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  publishDate,  author->{_id,name,image,link},  categories[]->,  },  body[]{    ...,    markDefs[]{      ...,      _type == "internalLink" => {        "slug": @.reference->slug      }    }  },    _id,  _createdAt,  title,  slug,  excerpt,  featured,  image {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  publishDate,  author->{_id,name,image,link},  categories[]->,  // "estReadingTime": round(length(pt::text(body)) / 5 / 180 ),  // "related": *[_type == "blogPost" && count(categories[@._ref in ^.categories[]._ref]) > 0 ] | order(publishDate desc, _createdAt desc) [0...2] {  //   slug,  //   title,  //   excerpt,  //   publishDate,  //   "date": coalesce(publishedDate, _createdAt),  //   "image": image  // },}
export type BlogPostQueryResult = {
  relatedPosts: Array<{
    _id: string;
    _createdAt: string;
    title: string | null;
    slug: Slug | null;
    excerpt: string | null;
    featured: boolean | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      blurDataURL: string | null;
      imageColor: string | null;
    } | null;
    publishDate: string | null;
    author: {
      _id: string;
      name: string | null;
      image: string | null;
      link: string | null;
    } | null;
    categories: Array<{
      _id: string;
      _type: "blogCategory";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      description?: string;
      priority?: number;
    }> | null;
  }> | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference?: never;
              _type: "internalLink";
              _key: string;
              slug: null;
            }
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
        markDefs: null;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  > | null;
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  featured: boolean | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  publishDate: string | null;
  author: {
    _id: string;
    name: string | null;
    image: string | null;
    link: string | null;
  } | null;
  categories: Array<{
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    priority?: number;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: blogPostMetadataQuery
// Query: *[_type == "blogPost" && slug.current == $slug][0] {      _id,  _createdAt,  title,  slug,  excerpt,  featured,  image {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  publishDate,  author->{_id,name,image,link},  categories[]->,}
export type BlogPostMetadataQueryResult = {
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  featured: boolean | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  publishDate: string | null;
  author: {
    _id: string;
    name: string | null;
    image: string | null;
    link: string | null;
  } | null;
  categories: Array<{
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    priority?: number;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: blogPostListQuery
// Query: *[_type == "blogPost" && defined(slug.current) && defined(publishDate)]  | order(publishDate desc) {      _id,  _createdAt,  title,  slug,  excerpt,  featured,  image {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  publishDate,  author->{_id,name,image,link},  categories[]->,}
export type BlogPostListQueryResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  featured: boolean | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  publishDate: string | null;
  author: {
    _id: string;
    name: string | null;
    image: string | null;
    link: string | null;
  } | null;
  categories: Array<{
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    priority?: number;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: blogPostListOfLatestQuery
// Query: *[_type == "blogPost" && defined(slug.current) && defined(publishDate)]  | order(publishDate desc) [0...$count] {      _id,  _createdAt,  title,  slug,  excerpt,  featured,  image {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  publishDate,  author->{_id,name,image,link},  categories[]->,}
export type BlogPostListOfLatestQueryResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  featured: boolean | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    blurDataURL: string | null;
    imageColor: string | null;
  } | null;
  publishDate: string | null;
  author: {
    _id: string;
    name: string | null;
    image: string | null;
    link: string | null;
  } | null;
  categories: Array<{
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    priority?: number;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: searchBlogQuery
// Query: *[_type == "blogPost" && defined(slug.current) && defined(publishDate) && _score > 0]  | score(title match $query || excerpt match $query || pt::text(body) match $query)  | order(_score desc) {  _score,    _id,  _createdAt,  title,  slug,  excerpt,  featured,  image {    ...,    "blurDataURL": asset->metadata.lqip,    "imageColor": asset->metadata.palette.dominant.background,  },  publishDate,  author->{_id,name,image,link},  categories[]->,}
export type SearchBlogQueryResult = Array<never>;

// Source: src/sanity/lib/queries.ts
// Variable: blogCategoryWithCountQuery
// Query: *[_type == "blogCategory"] {    name,  slug,  description,  priority,  "count": count(*[_type == "blogPost" && references(^._id)])} | order(count desc) [0...5]
export type BlogCategoryWithCountQueryResult = Array<{
  name: string | null;
  slug: Slug | null;
  description: string | null;
  priority: number | null;
  count: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: itemListQueryForSitemap
// Query: *[_type == "item" && visible == true && defined(slug.current) && defined(publishDate)] | order(_createdAt asc) {  _id,  _updatedAt,  "slug": slug.current,}
export type ItemListQueryForSitemapResult = Array<{
  _id: string;
  _updatedAt: string;
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: categoryListQueryForSitemap
// Query: *[_type == "category" && defined(slug.current)] | order(_createdAt asc) {  _id,  _updatedAt,  "slug": slug.current,  "count": count(*[_type == "item" && visible == true && defined(publishDate) && visible == true && references(^._id)])}
export type CategoryListQueryForSitemapResult = Array<{
  _id: string;
  _updatedAt: string;
  slug: string | null;
  count: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: tagListQueryForSitemap
// Query: *[_type == "tag" && defined(slug.current)] | order(_createdAt asc) {  _id,  _updatedAt,  "slug": slug.current,  "count": count(*[_type == "item" && visible == true && defined(publishDate) && visible == true && references(^._id)])}
export type TagListQueryForSitemapResult = Array<{
  _id: string;
  _updatedAt: string;
  slug: string | null;
  count: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: collectionListQueryForSitemap
// Query: *[_type == "collection" && defined(slug.current)] | order(_createdAt asc) {  _id,  _updatedAt,  "slug": slug.current,  "count": count(*[_type == "item" && visible == true && defined(publishDate) && visible == true && _id in ^.items[]._ref])}
export type CollectionListQueryForSitemapResult = Array<{
  _id: string;
  _updatedAt: string;
  slug: string | null;
  count: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: blogListQueryForSitemap
// Query: *[_type == "blogPost" && defined(slug.current) && defined(publishDate)] | order(publishDate desc, _createdAt asc) {  _id,  _updatedAt,  "slug": slug.current,}
export type BlogListQueryForSitemapResult = Array<{
  _id: string;
  _updatedAt: string;
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: blogCategoryListQueryForSitemap
// Query: *[_type == "blogCategory" && defined(slug.current)] | order(_createdAt asc) {  _id,  _updatedAt,  "slug": slug.current,  "count": count(*[_type == "blogPost" && defined(publishDate) && references(^._id)])}
export type BlogCategoryListQueryForSitemapResult = Array<{
  _id: string;
  _updatedAt: string;
  slug: string | null;
  count: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: pageListQueryForSitemap
// Query: *[_type == "page" && defined(slug.current)] | order(_createdAt asc) {  _id,  _updatedAt,  "slug": slug.current,}
export type PageListQueryForSitemapResult = Array<{
  _id: string;
  _updatedAt: string;
  slug: string | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "item" && visible == true && _id == $id][0] {\n  \n  _id,\n  _createdAt,\n  name,\n  slug,\n  description,\n  link,\n  affiliateLink,\n  sponsor,\n  sponsorStartDate,\n  sponsorEndDate,\n  featured,\n  icon {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  image {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  publishDate,\n  submitter{name,image,link},\n  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},\n  categories[]->,\n  tags[]->,\n\n}': ItemByIdQueryResult;
    '*[_type == "item" && visible == true && slug.current == $slug][0] {\n  \n  _id,\n  _createdAt,\n  name,\n  slug,\n  description,\n  link,\n  affiliateLink,\n  sponsor,\n  sponsorStartDate,\n  sponsorEndDate,\n  featured,\n  icon {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  image {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  publishDate,\n  submitter{name,image,link},\n  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},\n  categories[]->,\n  tags[]->,\n\n}': ItemInfoBySlugQueryResult;
    '*[_type == "item" && visible == true && _id == $id][0] {\n  \n  \n  _id,\n  _createdAt,\n  name,\n  slug,\n  description,\n  link,\n  affiliateLink,\n  sponsor,\n  sponsorStartDate,\n  sponsorEndDate,\n  featured,\n  icon {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  image {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  publishDate,\n  submitter{name,image,link},\n  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},\n  categories[]->,\n  tags[]->,\n\n  introduction,\n\n}': ItemFullInfoByIdQueryResult;
    '*[_type == "item" && visible == true && slug.current == $slug\n&& visible == true] [0] {\n  \n  introduction,\n  "related": *[_type == "item" && visible == true && defined(slug.current)\n    && defined(publishDate)\n    && visible == true\n    && !(sponsor == true && sponsorStartDate <= now() && sponsorEndDate > now())\n    && count(categories[@._ref in ^.categories[]._ref]) > 0 && _id != ^._id]\n    | order(publishDate desc, _createdAt desc) [0...3] {\n      \n  _id,\n  _createdAt,\n  name,\n  slug,\n  description,\n  link,\n  affiliateLink,\n  sponsor,\n  sponsorStartDate,\n  sponsorEndDate,\n  featured,\n  icon {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  image {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  publishDate,\n  submitter{name,image,link},\n  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},\n  categories[]->,\n  tags[]->,\n\n  },\n  \n  _id,\n  _createdAt,\n  name,\n  slug,\n  description,\n  link,\n  affiliateLink,\n  sponsor,\n  sponsorStartDate,\n  sponsorEndDate,\n  featured,\n  icon {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  image {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  publishDate,\n  submitter{name,image,link},\n  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},\n  categories[]->,\n  tags[]->,\n\n\n}': ItemFullInfoBySlugQueryResult;
    '*[_type == "item" && visible == true && defined(slug.current)\n  && defined(publishDate)\n  && visible == true\n  && !(sponsor == true && sponsorStartDate <= now() && sponsorEndDate > now())]\n  | order(coalesce(featured, false) desc, publishDate desc) {\n    \n  _id,\n  _createdAt,\n  name,\n  slug,\n  description,\n  link,\n  affiliateLink,\n  sponsor,\n  sponsorStartDate,\n  sponsorEndDate,\n  featured,\n  icon {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  image {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  publishDate,\n  submitter{name,image,link},\n  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},\n  categories[]->,\n  tags[]->,\n\n}': ItemListQueryResult;
    '*[_type == "item" && visible == true && defined(slug.current)\n  && defined(publishDate)\n  && visible == true\n  && sponsor == true\n  && sponsorStartDate <= now()\n  && sponsorEndDate >= now()]\n  | order(coalesce(featured, false) desc, publishDate desc) {\n    \n  _id,\n  _createdAt,\n  name,\n  slug,\n  description,\n  link,\n  affiliateLink,\n  sponsor,\n  sponsorStartDate,\n  sponsorEndDate,\n  featured,\n  icon {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  image {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  publishDate,\n  submitter{name,image,link},\n  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},\n  categories[]->,\n  tags[]->,\n\n}': SponsorItemListQueryResult;
    '*[_type == "item" && visible == true && defined(slug.current)\n  && defined(publishDate)\n  && visible == true\n  && !(sponsor == true && sponsorStartDate <= now() && sponsorEndDate > now())\n  && featured == true]\n  | order(coalesce(featured, false) desc, publishDate desc) [0...$count] {\n    \n  _id,\n  _createdAt,\n  name,\n  slug,\n  description,\n  link,\n  affiliateLink,\n  sponsor,\n  sponsorStartDate,\n  sponsorEndDate,\n  featured,\n  icon {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  image {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  publishDate,\n  submitter{name,image,link},\n  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},\n  categories[]->,\n  tags[]->,\n\n}': ItemListOfFeaturedQueryResult;
    '*[_type == "item" && visible == true && defined(slug.current)\n  && defined(publishDate)\n  && visible == true\n  && !(sponsor == true && sponsorStartDate <= now() && sponsorEndDate > now())]\n  | order(coalesce(featured, false) desc, publishDate desc) [0...$count] {\n    \n  _id,\n  _createdAt,\n  name,\n  slug,\n  description,\n  link,\n  affiliateLink,\n  sponsor,\n  sponsorStartDate,\n  sponsorEndDate,\n  featured,\n  icon {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  image {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  publishDate,\n  submitter{name,image,link},\n  "collections": *[_type=="collection" && references(^._id)]{_id,name,slug},\n  categories[]->,\n  tags[]->,\n\n}': ItemListOfLatestQueryResult;
    '*[_type == "collection" && defined(slug.current)]\n  | order(priority desc) {\n    \n  ...,\n  icon {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n\n}': CollectionListQueryResult;
    '*[_type == "collection" && slug.current == $slug][0] {\n  \n  ...,\n  icon {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n\n}': CollectionQueryResult;
    '*[_type=="group"] | order(priority desc, _createdAt asc) {\n  \n  ...,\n  "categories": *[_type==\'category\' && references(^._id)] | order(priority desc, _createdAt asc)\n  {\n    ...,\n  }\n\n}': GroupListQueryResult;
    '*[_type == "category" && defined(slug.current)]\n  | order(priority desc) {\n    \n  ...,\n\n}': CategoryListQueryResult;
    '*[_type == "category" && slug.current == $slug][0] {\n  \n  ...,\n\n}': CategoryQueryResult;
    '*[_type == "tag" && defined(slug.current)]\n  | order(slug.current asc) {\n    \n  ...,\n\n}': TagListQueryResult;
    '*[_type == "tag" && slug.current == $slug][0] {\n  \n  ...,\n\n}': TagQueryResult;
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    ...,\n    body[]{\n      ...,\n      markDefs[]{\n        ...,\n        _type == "internalLink" => {\n          "slug": @.reference->slug\n        }\n      }\n    },\n  }\n': PageQueryResult;
    '\n  *[_type == "blogCategory" && defined(slug.current)]\n  | order(priority desc) {\n    \n  name,\n  slug,\n  description,\n  priority,\n\n}': BlogCategoryListQueryResult;
    '\n  *[_type == "blogCategory" && slug.current == $slug][0] {\n    \n  name,\n  slug,\n  description,\n  priority,\n\n  }\n': BlogCategoryMetadateQueryResult;
    '\n  *[_type == "blogPost" && slug.current == $slug][0] {\n    \n  relatedPosts[]-> {\n    \n  _id,\n  _createdAt,\n  title,\n  slug,\n  excerpt,\n  featured,\n  image {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  publishDate,\n  author->{_id,name,image,link},\n  categories[]->,\n\n  },\n  body[]{\n    ...,\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        "slug": @.reference->slug\n      }\n    }\n  },\n  \n  _id,\n  _createdAt,\n  title,\n  slug,\n  excerpt,\n  featured,\n  image {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  publishDate,\n  author->{_id,name,image,link},\n  categories[]->,\n\n\n  // "estReadingTime": round(length(pt::text(body)) / 5 / 180 ),\n  // "related": *[_type == "blogPost" && count(categories[@._ref in ^.categories[]._ref]) > 0 ] | order(publishDate desc, _createdAt desc) [0...2] {\n  //   slug,\n  //   title,\n  //   excerpt,\n  //   publishDate,\n  //   "date": coalesce(publishedDate, _createdAt),\n  //   "image": image\n  // },\n\n}': BlogPostQueryResult;
    '\n  *[_type == "blogPost" && slug.current == $slug][0] {\n    \n  _id,\n  _createdAt,\n  title,\n  slug,\n  excerpt,\n  featured,\n  image {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  publishDate,\n  author->{_id,name,image,link},\n  categories[]->,\n\n}': BlogPostMetadataQueryResult;
    '\n  *[_type == "blogPost" && defined(slug.current) && defined(publishDate)]\n  | order(publishDate desc) {\n    \n  _id,\n  _createdAt,\n  title,\n  slug,\n  excerpt,\n  featured,\n  image {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  publishDate,\n  author->{_id,name,image,link},\n  categories[]->,\n\n}': BlogPostListQueryResult;
    '\n  *[_type == "blogPost" && defined(slug.current) && defined(publishDate)]\n  | order(publishDate desc) [0...$count] {\n    \n  _id,\n  _createdAt,\n  title,\n  slug,\n  excerpt,\n  featured,\n  image {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  publishDate,\n  author->{_id,name,image,link},\n  categories[]->,\n\n}': BlogPostListOfLatestQueryResult;
    '\n  *[_type == "blogPost" && defined(slug.current) && defined(publishDate) && _score > 0]\n  | score(title match $query || excerpt match $query || pt::text(body) match $query)\n  | order(_score desc) {\n  _score,\n  \n  _id,\n  _createdAt,\n  title,\n  slug,\n  excerpt,\n  featured,\n  image {\n    ...,\n    "blurDataURL": asset->metadata.lqip,\n    "imageColor": asset->metadata.palette.dominant.background,\n  },\n  publishDate,\n  author->{_id,name,image,link},\n  categories[]->,\n\n}': SearchBlogQueryResult;
    '\n  *[_type == "blogCategory"] {\n  \n  name,\n  slug,\n  description,\n  priority,\n\n  "count": count(*[_type == "blogPost" && references(^._id)])\n} | order(count desc) [0...5]': BlogCategoryWithCountQueryResult;
    '*[_type == "item" && visible == true && defined(slug.current) && defined(publishDate)] | order(_createdAt asc) {\n  _id,\n  _updatedAt,\n  "slug": slug.current,\n}': ItemListQueryForSitemapResult;
    '*[_type == "category" && defined(slug.current)] | order(_createdAt asc) {\n  _id,\n  _updatedAt,\n  "slug": slug.current,\n  "count": count(*[_type == "item" && visible == true && defined(publishDate) && visible == true && references(^._id)])\n}': CategoryListQueryForSitemapResult;
    '*[_type == "tag" && defined(slug.current)] | order(_createdAt asc) {\n  _id,\n  _updatedAt,\n  "slug": slug.current,\n  "count": count(*[_type == "item" && visible == true && defined(publishDate) && visible == true && references(^._id)])\n}': TagListQueryForSitemapResult;
    '*[_type == "collection" && defined(slug.current)] | order(_createdAt asc) {\n  _id,\n  _updatedAt,\n  "slug": slug.current,\n  "count": count(*[_type == "item" && visible == true && defined(publishDate) && visible == true && _id in ^.items[]._ref])\n}': CollectionListQueryForSitemapResult;
    '*[_type == "blogPost" && defined(slug.current) && defined(publishDate)] | order(publishDate desc, _createdAt asc) {\n  _id,\n  _updatedAt,\n  "slug": slug.current,\n}': BlogListQueryForSitemapResult;
    '*[_type == "blogCategory" && defined(slug.current)] | order(_createdAt asc) {\n  _id,\n  _updatedAt,\n  "slug": slug.current,\n  "count": count(*[_type == "blogPost" && defined(publishDate) && references(^._id)])\n}': BlogCategoryListQueryForSitemapResult;
    '*[_type == "page" && defined(slug.current)] | order(_createdAt asc) {\n  _id,\n  _updatedAt,\n  "slug": slug.current,\n}': PageListQueryForSitemapResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
