// Generated by the local OpenNext build before Wrangler bundles this entry.
// @ts-ignore OpenNext output is generated, not checked into source control.
import nextWorker from "./.open-next/worker.js";
import { maintainDatabase } from "./src/db/maintenance";
import { drainOutbox } from "./src/db/outbox";
import {
  drainNotifications,
  emailProvider,
} from "./src/services/notifications";
import { workerPublisher } from "./src/services/publisher";

export default {
  ...nextWorker,
  async scheduled(
    _controller: ScheduledController,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ) {
    ctx.waitUntil(
      (async () => {
        await maintainDatabase(env.DB);
        await drainOutbox(env.DB, workerPublisher(env));
        if (env.RESEND_API_KEY)
          await drainNotifications(
            env.DB,
            emailProvider({
              apiKey: env.RESEND_API_KEY,
              from: env.RESEND_EMAIL_FROM,
              audienceId: env.RESEND_AUDIENCE_ID,
            }),
            {
              siteUrl: env.NEXT_PUBLIC_APP_URL,
              adminEmail: env.RESEND_EMAIL_ADMIN,
            },
          );
      })(),
    );
  },
} satisfies ExportedHandler<CloudflareEnv>;
