import assert from "node:assert/strict";

const pixel = Uint8Array.from(
  Buffer.from(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=",
    "base64",
  ),
);

/** Exercise the installed AI SDK over its HTTP protocol without provider access. */
export async function aiHttpResponse(request) {
  const url = new URL(request.url);
  if (url.hostname === "example.com" && url.pathname === "/local-ai")
    return new Response("<html><title>Local AI listing</title></html>", {
      headers: { "content-type": "text/html" },
    });
  if (url.hostname === "example.com" && url.pathname === "/local-redirect")
    return new Response(null, {
      status: 302,
      headers: { location: "https://127.0.0.1/private" },
    });
  if (
    (url.hostname === "example.com" && url.pathname === "/local-image.png") ||
    (url.hostname === "s2.googleusercontent.com" &&
      url.pathname === "/s2/favicons")
  )
    return new Response(pixel, { headers: { "content-type": "image/png" } });
  if (url.hostname !== "api.openai.com") return null;
  assert.equal(request.method, "POST");
  assert.equal(url.pathname, "/v1/chat/completions");
  const body = await request.json();
  assert.equal(body.model, "local-fixture-model");
  assert.equal(body.max_tokens, 2500);
  assert.equal(body.response_format.type, "json_schema");
  return Response.json({
    id: "chatcmpl_local",
    model: body.model,
    choices: [
      {
        index: 0,
        message: {
          role: "assistant",
          content: JSON.stringify({
            name: "Local AI listing",
            description: "Generated by an offline provider fixture",
            introduction: "## Local AI content\n\nRequires first review.",
            categories: ["Local category", "Invented category"],
            tags: ["Local tag", "Invented tag"],
            image: "https://example.com/local-image.png",
            icon: "https://example.com/local-image.png",
          }),
        },
        finish_reason: "stop",
      },
    ],
    usage: { prompt_tokens: 20, completion_tokens: 50 },
  });
}
